# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0008_auto_20170725_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fscjob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailaddress', models.EmailField(max_length=254)),
                ('halfmap1file', models.FileField(upload_to='')),
                ('halfmap2file', models.FileField(upload_to='')),
                ('fullmapfile', models.FileField(upload_to='')),
                ('apix', models.FloatField()),
                ('maskfile', models.FileField(blank=True, upload_to='')),
                ('coneangle', models.FloatField(default=20)),
                ('fsccutoff', models.FloatField(default=0.143)),
                ('sphericitythresh', models.FloatField(default=0.5)),
                ('highpassilfter', models.FloatField(default=150.0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
