# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0009_auto_20170725_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fscjob',
            name='apix',
            field=models.FloatField(null=True),
        ),
    ]
