# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-07-25 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0010_auto_20170725_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fscjob',
            name='highpassilfter',
        ),
        migrations.AddField(
            model_name='fscjob',
            name='highpassfilter',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='fscjob',
            name='coneangle',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
        migrations.AlterField(
            model_name='fscjob',
            name='fsccutoff',
            field=models.DecimalField(decimal_places=2, default=0.143, max_digits=5),
        ),
        migrations.AlterField(
            model_name='fscjob',
            name='sphericitythresh',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=5),
        ),
    ]
