# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-07-25 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0011_auto_20170725_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fscjob',
            name='coneangle',
            field=models.FloatField(default=20),
        ),
        migrations.AlterField(
            model_name='fscjob',
            name='fsccutoff',
            field=models.FloatField(default=0.143),
        ),
        migrations.AlterField(
            model_name='fscjob',
            name='highpassfilter',
            field=models.FloatField(default=150.0),
        ),
        migrations.AlterField(
            model_name='fscjob',
            name='sphericitythresh',
            field=models.FloatField(default=0.5),
        ),
    ]
