# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0014_auto_20170725_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='fscjob',
            name='uniquefolder',
            field=models.CharField(default='69d88c23e083deaf1bb8', max_length=20),
        ),
    ]
