# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0016_auto_20170726_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fscjob',
            name='password',
            field=models.CharField(default='8e5d6c56aa', max_length=20),
        ),
        migrations.AlterField(
            model_name='fscjob',
            name='uniquefolder',
            field=models.CharField(default='05dfee0837fa264ad0c5', max_length=20),
        ),
    ]
