# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0017_auto_20170727_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fscjob',
            name='password',
            field=models.CharField(default='84a346e17f', max_length=20),
        ),
        migrations.AlterField(
            model_name='fscjob',
            name='uniquefolder',
            field=models.CharField(default='761c23c5d3fef8894911', max_length=20),
        ),
    ]
