# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0021_auto_20170727_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='fscjob',
            name='completefile',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='fscjob',
            name='jobname',
            field=models.CharField(default='3dfsc_run', max_length=15),
        ),
        migrations.AlterField(
            model_name='fscjob',
            name='password',
            field=models.CharField(default='020816d2b5', max_length=20),
        ),
        migrations.AlterField(
            model_name='fscjob',
            name='uniquefolder',
            field=models.CharField(default='1b0b21901dffc0eb4655', max_length=20),
        ),
    ]
