# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0024_auto_20170728_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fscjob',
            name='password',
            field=models.CharField(default='c39875bd89', max_length=20),
        ),
        migrations.AlterField(
            model_name='fscjob',
            name='uniquefolder',
            field=models.CharField(default='4102662fd2fe312fb51b', max_length=20),
        ),
    ]
