# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0025_auto_20170728_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fscjob',
            name='password',
            field=models.CharField(default='d02fa7d25f', max_length=20),
        ),
        migrations.AlterField(
            model_name='fscjob',
            name='uniquefolder',
            field=models.CharField(default='8b4428d53c837afc2fc1', max_length=20),
        ),
    ]
