# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0026_auto_20170728_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fscjob',
            name='halfmap1file',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='fscjob',
            name='password',
            field=models.CharField(default='7907d7e726', max_length=20),
        ),
        migrations.AlterField(
            model_name='fscjob',
            name='uniquefolder',
            field=models.CharField(default='fbd33726221fed44730d', max_length=20),
        ),
    ]
