# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0027_auto_20170729_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fscjob',
            name='completefile',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='fscjob',
            name='fullmapfile',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='fscjob',
            name='halfmap2file',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='fscjob',
            name='maskfile',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='fscjob',
            name='password',
            field=models.CharField(default='299933f90e', max_length=20),
        ),
        migrations.AlterField(
            model_name='fscjob',
            name='uniquefolder',
            field=models.CharField(default='4512e4d26e4f8d803cb4', max_length=20),
        ),
    ]
