# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0028_auto_20170729_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fscjob',
            name='completefile',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='fscjob',
            name='fullmapfile',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='fscjob',
            name='halfmap1file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='fscjob',
            name='halfmap2file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='fscjob',
            name='maskfile',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='fscjob',
            name='password',
            field=models.CharField(default='48639ac394', max_length=20),
        ),
        migrations.AlterField(
            model_name='fscjob',
            name='uniquefolder',
            field=models.CharField(default='402ffdfddae0a6e75e74', max_length=20),
        ),
    ]
