# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0029_auto_20170729_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fscjob',
            name='apix',
            field=models.FloatField(default=1.1, verbose_name='Pixel Size (Angstrom)'),
        ),
        migrations.AlterField(
            model_name='fscjob',
            name='completefile',
            field=models.FileField(upload_to='', verbose_name='Results file name'),
        ),
        migrations.AlterField(
            model_name='fscjob',
            name='coneangle',
            field=models.FloatField(default=20.0, verbose_name='Cone angle'),
        ),
        migrations.AlterField(
            model_name='fscjob',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='fscjob',
            name='emailaddress',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='fscjob',
            name='fsccutoff',
            field=models.FloatField(default=0.143, verbose_name='FSC Cutoff'),
        ),
        migrations.AlterField(
            model_name='fscjob',
            name='fullmapfile',
            field=models.FileField(upload_to='', verbose_name='Full map file'),
        ),
        migrations.AlterField(
            model_name='fscjob',
            name='halfmap1file',
            field=models.FileField(upload_to='', verbose_name='Half-map 1 file'),
        ),
        migrations.AlterField(
            model_name='fscjob',
            name='halfmap2file',
            field=models.FileField(upload_to='', verbose_name='Half-map 2 file'),
        ),
        migrations.AlterField(
            model_name='fscjob',
            name='highpassfilter',
            field=models.FloatField(default=150.0, verbose_name='High-pass filter (Angstrom)'),
        ),
        migrations.AlterField(
            model_name='fscjob',
            name='jobname',
            field=models.CharField(default='3dfsc_run', max_length=15, verbose_name='Job Name'),
        ),
        migrations.AlterField(
            model_name='fscjob',
            name='maskfile',
            field=models.FileField(blank=True, upload_to='', verbose_name='Mask file'),
        ),
        migrations.AlterField(
            model_name='fscjob',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date last modified'),
        ),
        migrations.AlterField(
            model_name='fscjob',
            name='password',
            field=models.CharField(default='76eaff1de8', max_length=20, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='fscjob',
            name='sphericitythresh',
            field=models.FloatField(default=0.5, verbose_name='Sphericity Threshold'),
        ),
        migrations.AlterField(
            model_name='fscjob',
            name='uniquefolder',
            field=models.CharField(default='5cbea3e04b7abf6cfd5a', max_length=20, verbose_name='Unique folder name'),
        ),
    ]
