# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0030_auto_20170801_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fscjob',
            name='password',
            field=models.CharField(default='f2ace8b16e', max_length=20, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='fscjob',
            name='uniquefolder',
            field=models.CharField(default='884b4009d51008d40a7f', max_length=20, verbose_name='Unique folder name'),
        ),
    ]
