# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0032_auto_20170804_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fscjob',
            name='password',
            field=models.CharField(default='defaultpassword', max_length=20, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='fscjob',
            name='uniquefolder',
            field=models.CharField(default='uniquefolder', max_length=20, verbose_name='Unique folder name'),
        ),
    ]
