# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-03 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0034_fscjob_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fscjob',
            name='ftplot_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='', verbose_name='FTPlot jpg file'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fscjob',
            name='histogram_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='', verbose_name='Histogram png file'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fscjob',
            name='plots_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='', verbose_name='Plots jpg file'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fscjob',
            name='completefile',
            field=models.FileField(upload_to='', verbose_name='Zipped results file'),
        ),
    ]
