# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-04 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0035_auto_20180303_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fscjob',
            name='ftplot_file',
            field=models.FileField(null=True, upload_to='', verbose_name='FTPlot jpg file'),
        ),
        migrations.AlterField(
            model_name='fscjob',
            name='histogram_file',
            field=models.FileField(null=True, upload_to='', verbose_name='Histogram png file'),
        ),
        migrations.AlterField(
            model_name='fscjob',
            name='plots_file',
            field=models.FileField(null=True, upload_to='', verbose_name='Plots jpg file'),
        ),
    ]
