# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-10 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0037_fscjob_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fscjob',
            name='jobname',
            field=models.CharField(default='', max_length=35, verbose_name='Job Name'),
        ),
    ]
